### ISSUE TITLE
Arch Linux support

### ISSUE THREAD

**Issue by Seeker14491** [ColorsWind/WSL-Port-Forwarding#7]
I use Arch in WSL, and the following error is produced when running the program:

```
$ port_forwarding
hostname: invalid option -- 'I'
Try 'hostname --help' or 'hostname --usage' for more information.
You need Windows administrator privileges to use this script().
```

This is due to the [`hostname` command used in Arch](https://man.archlinux.org/man/hostname.1.en) not supporting the `-I`/`--all-ip-addresses` flag.

**Comment by ColorsWind** [comment]
Now work on Arch, thanks for your feedback.

**Comment by Seeker14491** [comment]
Thanks for the quick fix, though there is one more issue. The script uses the `netstat` command from the `net-tools` Arch package, which is not installed by default in Arch because it's been [deprecated since 2011](https://archlinux.org/news/deprecation-of-net-tools/). If `netstat` isn't available, the script silently fails to find any ports.

The modern replacement for `netstat` is [`ss` from the `iproute2` package](https://man7.org/linux/man-pages/man8/ss.8.html), which *is* installed by default in Arch (and other distros). I think it should be used instead.

**Comment by ColorsWind** [comment]
I agree, since `netstat` requires manual installation of `net-tools` while `ss` is provided by default. However, the output of `ss -tpln` is not exactly equivalent to that of `netstat -tpln`. I need some time to ensure it works correctly in different situations. Thanks again for your suggestion, I have opened a new issue #8 .
